from pydantic import BaseModel, Field
from typing import Annotated, Literal
from operator import add

# the state of the agent is stored in this schema, which includes the messages exchanged, the curated question, the prompt context, the safety of the generated SQL query, 
# the generated SQL query itself, the execution result of that query, and the final answer provided by the agent.
class AgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(..., description="List of messages exchanged with the agent")
    user_question: str = Field(..., description="The original user question that initiated the interaction with the agent")
    curated_question : str = Field(..., description="Curated user question for the agent")
    prompt_query_context : str = Field(..., description="A detailed prompt with sql DB content to help the agent to generate sql query")
    generated_sql_query : str = Field(..., description="The SQL query generated by the agent based on the prompt and context")
    is_safe : Literal["Yes", "No"] = Field(..., description="Indicates whether the generated SQL query is safe to execute or not")
    comments : str = Field(..., description="Comments or feedback from the agent regarding the safety of the generated SQL query")
    sql_query_execution_result : str = Field(..., description="The result of executing the generated SQL query on the database")
    final_answer : str = Field(..., description="The final answer provided by the agent after processing the SQL query execution result")



class JudgeSchema(BaseModel):
    answer : Literal["Yes", "No"] = Field(..., description="Indicates whether the final answer provided by the agent is correct or not")
    comments : str = Field(..., description="Comments or feedback from the judge regarding the final answer provided by the agent")



class ETLAgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(..., description="List of messages to b processed by the ETL agent")


class RouterSchema(BaseModel):
    answer: Literal["sql","etl"] = Field(..., description="Indicates whether the user's question is related to SQL or ETL operations")
    comments: str = Field(..., description="Additional comments or feedback regarding the classification of the user's question")

class DataAgentSchema(BaseModel):
    messages : Annotated[list,add] = Field(..., description="List of messages to be processed by the Data agent")
    route_response : str = Field(..., description="The response from the router indicating whether to route to SQL or ETL operations")